DATABASE USE `mydatabase`


CREATE TABLE `myList` (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(55) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
